// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '', //this part you should use your own api key
    appId: '1:1020204058732:android:2cd9477db57d1067423049',
    messagingSenderId: '1020204058732',
    projectId: 'my-notes-meh',
    storageBucket: 'my-notes-meh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTVyKm1yyG3TMYeY-DMiqtAV9jh8EdA6M',
    appId: '1:1020204058732:ios:1a1561d8336abf21423049',
    messagingSenderId: '1020204058732',
    projectId: 'my-notes-meh',
    storageBucket: 'my-notes-meh.appspot.com',
    iosClientId:
        '1020204058732-hnj4githbl3vsc1vd67ph3933m7b23qp.apps.googleusercontent.com',
    iosBundleId: 'com.mehran.mynotes',
  );
}
